### ISSUE TITLE
Issue on install

### ISSUE THREAD

**Issue by gah242s** [CiviCooP/be.werkmetzin.wpcivi#2]
When I click the Install button on the extension, I get:

CiviCRM_API3_Exception: "Could not find the folder [civicrm.files]/ext//be.werkmetzin.wpcivi/resources/ which is required for extension be.werkmetzin.wpcivi in CRM_Wpcivi_ConfigItems::__construct.It does not exist or is not a folder, contact your system administrator"
#0 [Absolute dir for WP]plugins/files/civicrm/ext/be.werkmetzin.wpcivi-master/wpcivi.php(51): civicrm_api3("WpCivi", "Initialize", (Array:0))
#1 [Absolute dir for WP]plugins/civicrm/civicrm/CRM/Extension/Manager/Module.php(76): wpcivi_civicrm_enable()
#2 [Absolute dir for WP]plugins/civicrm/civicrm/CRM/Extension/Manager/Module.php(49): CRM_Extension_Manager_Module->callHook(Object(CRM_Extension_Info), "enable")
#3 [Absolute dir for WP]plugins/civicrm/civicrm/CRM/Extension/Manager.php(229): CRM_Extension_Manager_Module->onPreInstall(Object(CRM_Extension_Info))
#4 [Absolute dir for WP]plugins/civicrm/civicrm/CRM/Admin/Form/Extensions.php(181): CRM_Extension_Manager->install((Array:1))
#5 [Absolute dir for WP]plugins/civicrm/civicrm/CRM/Core/Form.php(423): CRM_Admin_Form_Extensions->postProcess()
#6 [Absolute dir for WP]plugins/civicrm/civicrm/CRM/Core/StateMachine.php(160): CRM_Core_Form->mainProcess()
#7 [Absolute dir for WP]plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Next.php(61): CRM_Core_StateMachine->perform(Object(CRM_Admin_Form_Extensions), "next", "Next")
#8 [Absolute dir for WP]plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Admin_Form_Extensions), "next")
#9 [Absolute dir for WP]plugins/civicrm/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Admin_Form_Extensions), "next")
#10 [Absolute dir for WP]plugins/civicrm/civicrm/CRM/Core/Controller.php(351): HTML_QuickForm_Page->handle("next")
#11 [Absolute dir for WP]plugins/civicrm/civicrm/CRM/Core/Page/Basic.php(384): CRM_Core_Controller->run()
#12 [Absolute dir for WP]plugins/civicrm/civicrm/CRM/Core/Page/Basic.php(168): CRM_Core_Page_Basic->edit(1, NULL)
#13 [Absolute dir for WP]plugins/civicrm/civicrm/CRM/Admin/Page/Extensions.php(121): CRM_Core_Page_Basic->run()
#14 [Absolute dir for WP]plugins/civicrm/civicrm/CRM/Core/Invoke.php(312): CRM_Admin_Page_Extensions->run((Array:3), NULL)
#15 [Absolute dir for WP]plugins/civicrm/civicrm/CRM/Core/Invoke.php(86): CRM_Core_Invoke::runItem((Array:13))
#16 [Absolute dir for WP]plugins/civicrm/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:3))
#17 [Absolute dir for WP]plugins/civicrm/civicrm.php(1227): CRM_Core_Invoke::invoke((Array:3))
#18 [internal function](): CiviCRM_For_WordPress->invoke("")
#19 [Absolute dir for WP]plugins/plugin.php(524): call_user_func_array((Array:2), (Array:1))
#20 [Absolute dir for WP]wp-admin/admin.php(222): do_action("toplevel_page_CiviCRM")
#21 {main}

Permissions on the extension folder are the same as other working added extensions.  The folder does exist when doing a "ls" command.  I've attempted with a dir name with the -master and without.  Ideas?

WP 4.6, CiviCRM 4.7.11

**Comment by ErikHommel** [comment]
@gah242s Looks like there is a double slash in the folder tree:
[civicrm.files]/ext//bse.werkmetzin.wpcivi/resources/ 
Can you try and fix that?

**Comment by danielpomlett** [comment]
I'm getting the same error on install as gah242s. I did originally notice there was a double slash, but I still get the error even after removing it. I've checked it loads of times and I'm sure the 'resources' directory it's looking for is in the place it says it can't find it. Any ideas?

**Comment by gah242s** [comment]
Wish I could say I got this working.  Unfortunately, after playing with it for a while, I had to drop it and haven't gotten back.  Sorry.

**Comment by ErikHommel** [comment]
@gah242s this is a specific extension for a specific problem with a specific customer. We like to share it so you can pick it up as a base for your own project. It is not meant as an extension that will simply work and I would be utterly amazed if it does (far too many dependencies on specific configuration). 
The resources issue is because the extension is not CiviCRM 4.7 compatible as the customer it is developed for does not use 4.7. The error is because from 4.7 there are system configs for paths, and the extension does not cater for it. (see the [civicrm.files] part of the path).

**Comment by gah242s** [comment]
Thanks for the additional explanation.  It looks as though there may be new direction with a few other plugins that will take care of this need and provide additional benefits with 4.7.  Thanks for putting it out there though.
